@startuml
'-----------------------------------
' UML concepts illustrated
' JMB 2020
'-----------------------------------

!include config.cfg
'skinparam classAttributeIconSize 0

class Contexte {
Strategie strategie;
+contexte() {strategie.algorithme();}
}

abstract class Strategie {
{abstract} +algorithme()
}

class StrategieConcreteA {
+algorithme()
}

class StrategieConcreteB {
+algorithme()
}

class C as "..." {
+algorithme()
}

'Strategie <|-- StrategieConcreteA
'Strategie <|-- StrategieConcreteB
'Strategie <|-- C

'Contexte --> "+strategie" Strategie

@enduml
